//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuestoDeQuipes.SuplidoraQuisqueyanaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden", Namespace="http://schemas.datacontract.org/2004/07/SuplidoraQuisqueyanaService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class Orden : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadOrdenadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDeCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDeCuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadOrdenada {
            get {
                return this.CantidadOrdenadaField;
            }
            set {
                if ((this.CantidadOrdenadaField.Equals(value) != true)) {
                    this.CantidadOrdenadaField = value;
                    this.RaisePropertyChanged("CantidadOrdenada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeOrden {
            get {
                return this.FechaDeOrdenField;
            }
            set {
                if ((this.FechaDeOrdenField.Equals(value) != true)) {
                    this.FechaDeOrdenField = value;
                    this.RaisePropertyChanged("FechaDeOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDeArticulo {
            get {
                return this.NombreDeArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeArticuloField, value) != true)) {
                    this.NombreDeArticuloField = value;
                    this.RaisePropertyChanged("NombreDeArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDeCuenta {
            get {
                return this.NombreDeCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDeCuentaField, value) != true)) {
                    this.NombreDeCuentaField = value;
                    this.RaisePropertyChanged("NombreDeCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDeCuenta {
            get {
                return this.NumeroDeCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDeCuentaField, value) != true)) {
                    this.NumeroDeCuentaField = value;
                    this.RaisePropertyChanged("NumeroDeCuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/SuplidoraQuisqueyanaService.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadProveidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallesDeOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDeFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden OrdenOriginalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadProveida {
            get {
                return this.CantidadProveidaField;
            }
            set {
                if ((this.CantidadProveidaField.Equals(value) != true)) {
                    this.CantidadProveidaField = value;
                    this.RaisePropertyChanged("CantidadProveida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetallesDeOrden {
            get {
                return this.DetallesDeOrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesDeOrdenField, value) != true)) {
                    this.DetallesDeOrdenField = value;
                    this.RaisePropertyChanged("DetallesDeOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDeFactura {
            get {
                return this.NumeroDeFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDeFacturaField, value) != true)) {
                    this.NumeroDeFacturaField = value;
                    this.RaisePropertyChanged("NumeroDeFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden OrdenOriginal {
            get {
                return this.OrdenOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenOriginalField, value) != true)) {
                    this.OrdenOriginalField = value;
                    this.RaisePropertyChanged("OrdenOriginal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuplidoraQuisqueyanaService.ISuplidoraQuisqueyanaAPI")]
    public interface ISuplidoraQuisqueyanaAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuplidoraQuisqueyanaAPI/EnviarOrden", ReplyAction="http://tempuri.org/ISuplidoraQuisqueyanaAPI/EnviarOrdenResponse")]
        void EnviarOrden(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuplidoraQuisqueyanaAPI/EnviarOrden", ReplyAction="http://tempuri.org/ISuplidoraQuisqueyanaAPI/EnviarOrdenResponse")]
        System.IAsyncResult BeginEnviarOrden(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida, System.AsyncCallback callback, object asyncState);
        
        void EndEnviarOrden(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuplidoraQuisqueyanaAPI/OrdenCompletada", ReplyAction="http://tempuri.org/ISuplidoraQuisqueyanaAPI/OrdenCompletadaResponse")]
        PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura OrdenCompletada();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuplidoraQuisqueyanaAPI/OrdenCompletada", ReplyAction="http://tempuri.org/ISuplidoraQuisqueyanaAPI/OrdenCompletadaResponse")]
        System.IAsyncResult BeginOrdenCompletada(System.AsyncCallback callback, object asyncState);
        
        PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura EndOrdenCompletada(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuplidoraQuisqueyanaAPIChannel : PuestoDeQuipes.SuplidoraQuisqueyanaService.ISuplidoraQuisqueyanaAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenCompletadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public OrdenCompletadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuplidoraQuisqueyanaAPIClient : System.ServiceModel.ClientBase<PuestoDeQuipes.SuplidoraQuisqueyanaService.ISuplidoraQuisqueyanaAPI>, PuestoDeQuipes.SuplidoraQuisqueyanaService.ISuplidoraQuisqueyanaAPI {
        
        private BeginOperationDelegate onBeginEnviarOrdenDelegate;
        
        private EndOperationDelegate onEndEnviarOrdenDelegate;
        
        private System.Threading.SendOrPostCallback onEnviarOrdenCompletedDelegate;
        
        private BeginOperationDelegate onBeginOrdenCompletadaDelegate;
        
        private EndOperationDelegate onEndOrdenCompletadaDelegate;
        
        private System.Threading.SendOrPostCallback onOrdenCompletadaCompletedDelegate;
        
        public SuplidoraQuisqueyanaAPIClient() {
        }
        
        public SuplidoraQuisqueyanaAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuplidoraQuisqueyanaAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuplidoraQuisqueyanaAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuplidoraQuisqueyanaAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EnviarOrdenCompleted;
        
        public event System.EventHandler<OrdenCompletadaCompletedEventArgs> OrdenCompletadaCompleted;
        
        public void EnviarOrden(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida) {
            base.Channel.EnviarOrden(ordenRecibida);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEnviarOrden(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnviarOrden(ordenRecibida, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndEnviarOrden(System.IAsyncResult result) {
            base.Channel.EndEnviarOrden(result);
        }
        
        private System.IAsyncResult OnBeginEnviarOrden(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida = ((PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden)(inValues[0]));
            return this.BeginEnviarOrden(ordenRecibida, callback, asyncState);
        }
        
        private object[] OnEndEnviarOrden(System.IAsyncResult result) {
            this.EndEnviarOrden(result);
            return null;
        }
        
        private void OnEnviarOrdenCompleted(object state) {
            if ((this.EnviarOrdenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnviarOrdenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnviarOrdenAsync(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida) {
            this.EnviarOrdenAsync(ordenRecibida, null);
        }
        
        public void EnviarOrdenAsync(PuestoDeQuipes.SuplidoraQuisqueyanaService.Orden ordenRecibida, object userState) {
            if ((this.onBeginEnviarOrdenDelegate == null)) {
                this.onBeginEnviarOrdenDelegate = new BeginOperationDelegate(this.OnBeginEnviarOrden);
            }
            if ((this.onEndEnviarOrdenDelegate == null)) {
                this.onEndEnviarOrdenDelegate = new EndOperationDelegate(this.OnEndEnviarOrden);
            }
            if ((this.onEnviarOrdenCompletedDelegate == null)) {
                this.onEnviarOrdenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnviarOrdenCompleted);
            }
            base.InvokeAsync(this.onBeginEnviarOrdenDelegate, new object[] {
                        ordenRecibida}, this.onEndEnviarOrdenDelegate, this.onEnviarOrdenCompletedDelegate, userState);
        }
        
        public PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura OrdenCompletada() {
            return base.Channel.OrdenCompletada();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginOrdenCompletada(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginOrdenCompletada(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura EndOrdenCompletada(System.IAsyncResult result) {
            return base.Channel.EndOrdenCompletada(result);
        }
        
        private System.IAsyncResult OnBeginOrdenCompletada(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginOrdenCompletada(callback, asyncState);
        }
        
        private object[] OnEndOrdenCompletada(System.IAsyncResult result) {
            PuestoDeQuipes.SuplidoraQuisqueyanaService.Factura retVal = this.EndOrdenCompletada(result);
            return new object[] {
                    retVal};
        }
        
        private void OnOrdenCompletadaCompleted(object state) {
            if ((this.OrdenCompletadaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OrdenCompletadaCompleted(this, new OrdenCompletadaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OrdenCompletadaAsync() {
            this.OrdenCompletadaAsync(null);
        }
        
        public void OrdenCompletadaAsync(object userState) {
            if ((this.onBeginOrdenCompletadaDelegate == null)) {
                this.onBeginOrdenCompletadaDelegate = new BeginOperationDelegate(this.OnBeginOrdenCompletada);
            }
            if ((this.onEndOrdenCompletadaDelegate == null)) {
                this.onEndOrdenCompletadaDelegate = new EndOperationDelegate(this.OnEndOrdenCompletada);
            }
            if ((this.onOrdenCompletadaCompletedDelegate == null)) {
                this.onOrdenCompletadaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOrdenCompletadaCompleted);
            }
            base.InvokeAsync(this.onBeginOrdenCompletadaDelegate, null, this.onEndOrdenCompletadaDelegate, this.onOrdenCompletadaCompletedDelegate, userState);
        }
    }
}
