//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EntityDataModel", "ClienteOrden", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Cliente), "Orden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Orden), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "ProductoOrden", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Producto), "Orden", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Orden), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "ProductoEspecial", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Producto), "Especial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Especial), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "ProductoIngrediente", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Producto), "Ingrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Ingrediente), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "InventarioIngrediente", "Inventario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Inventario), "Ingrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Ingrediente), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "UnidadIngrediente", "Unidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Unidad), "Ingrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Ingrediente), true)]
[assembly: EdmRelationshipAttribute("EntityDataModel", "UnidadInventario", "Unidad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PuestoDeQuipes.Models.Entity.Unidad), "Inventario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PuestoDeQuipes.Models.Entity.Inventario), true)]

#endregion

namespace PuestoDeQuipes.Models.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityDataModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntityDataModelContainer object using the connection string found in the 'EntityDataModelContainer' section of the application configuration file.
        /// </summary>
        public EntityDataModelContainer() : base("name=EntityDataModelContainer", "EntityDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityDataModelContainer object.
        /// </summary>
        public EntityDataModelContainer(string connectionString) : base(connectionString, "EntityDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityDataModelContainer object.
        /// </summary>
        public EntityDataModelContainer(EntityConnection connection) : base(connection, "EntityDataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Orden> Ordenes
        {
            get
            {
                if ((_Ordenes == null))
                {
                    _Ordenes = base.CreateObjectSet<Orden>("Ordenes");
                }
                return _Ordenes;
            }
        }
        private ObjectSet<Orden> _Ordenes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Producto> Productos
        {
            get
            {
                if ((_Productos == null))
                {
                    _Productos = base.CreateObjectSet<Producto>("Productos");
                }
                return _Productos;
            }
        }
        private ObjectSet<Producto> _Productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Especial> Especiales
        {
            get
            {
                if ((_Especiales == null))
                {
                    _Especiales = base.CreateObjectSet<Especial>("Especiales");
                }
                return _Especiales;
            }
        }
        private ObjectSet<Especial> _Especiales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingrediente> Ingredientes
        {
            get
            {
                if ((_Ingredientes == null))
                {
                    _Ingredientes = base.CreateObjectSet<Ingrediente>("Ingredientes");
                }
                return _Ingredientes;
            }
        }
        private ObjectSet<Ingrediente> _Ingredientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Inventario> Inventarios
        {
            get
            {
                if ((_Inventarios == null))
                {
                    _Inventarios = base.CreateObjectSet<Inventario>("Inventarios");
                }
                return _Inventarios;
            }
        }
        private ObjectSet<Inventario> _Inventarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Unidad> Unidades
        {
            get
            {
                if ((_Unidades == null))
                {
                    _Unidades = base.CreateObjectSet<Unidad>("Unidades");
                }
                return _Unidades;
            }
        }
        private ObjectSet<Unidad> _Unidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Configuracion> Configuraciones
        {
            get
            {
                if ((_Configuraciones == null))
                {
                    _Configuraciones = base.CreateObjectSet<Configuracion>("Configuraciones");
                }
                return _Configuraciones;
            }
        }
        private ObjectSet<Configuracion> _Configuraciones;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ordenes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrdenes(Orden orden)
        {
            base.AddObject("Ordenes", orden);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductos(Producto producto)
        {
            base.AddObject("Productos", producto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Especiales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEspeciales(Especial especial)
        {
            base.AddObject("Especiales", especial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredientes(Ingrediente ingrediente)
        {
            base.AddObject("Ingredientes", ingrediente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Inventarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInventarios(Inventario inventario)
        {
            base.AddObject("Inventarios", inventario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Unidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnidades(Unidad unidad)
        {
            base.AddObject("Unidades", unidad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Configuraciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfiguraciones(Configuracion configuracion)
        {
            base.AddObject("Configuraciones", configuracion);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="clienteId">Initial value of the ClienteId property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="telefono">Initial value of the Telefono property.</param>
        public static Cliente CreateCliente(global::System.Int32 clienteId, global::System.String nombre, global::System.String apellido, global::System.String direccion, global::System.String email, global::System.String telefono)
        {
            Cliente cliente = new Cliente();
            cliente.ClienteId = clienteId;
            cliente.Nombre = nombre;
            cliente.Apellido = apellido;
            cliente.Direccion = direccion;
            cliente.Email = email;
            cliente.Telefono = telefono;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteId
        {
            get
            {
                return _ClienteId;
            }
            set
            {
                if (_ClienteId != value)
                {
                    OnClienteIdChanging(value);
                    ReportPropertyChanging("ClienteId");
                    _ClienteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClienteId");
                    OnClienteIdChanged();
                }
            }
        }
        private global::System.Int32 _ClienteId;
        partial void OnClienteIdChanging(global::System.Int32 value);
        partial void OnClienteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ClienteOrden", "Orden")]
        public EntityCollection<Orden> Ordenes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orden>("EntityDataModel.ClienteOrden", "Orden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orden>("EntityDataModel.ClienteOrden", "Orden", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Configuracion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Configuracion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Configuracion object.
        /// </summary>
        /// <param name="configuracionId">Initial value of the ConfiguracionId property.</param>
        /// <param name="config1">Initial value of the Config1 property.</param>
        /// <param name="config2">Initial value of the Config2 property.</param>
        /// <param name="config3">Initial value of the Config3 property.</param>
        /// <param name="config4">Initial value of the Config4 property.</param>
        /// <param name="config5">Initial value of the Config5 property.</param>
        /// <param name="config6">Initial value of the Config6 property.</param>
        public static Configuracion CreateConfiguracion(global::System.Int32 configuracionId, global::System.String config1, global::System.String config2, global::System.String config3, global::System.String config4, global::System.String config5, global::System.String config6)
        {
            Configuracion configuracion = new Configuracion();
            configuracion.ConfiguracionId = configuracionId;
            configuracion.Config1 = config1;
            configuracion.Config2 = config2;
            configuracion.Config3 = config3;
            configuracion.Config4 = config4;
            configuracion.Config5 = config5;
            configuracion.Config6 = config6;
            return configuracion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfiguracionId
        {
            get
            {
                return _ConfiguracionId;
            }
            set
            {
                if (_ConfiguracionId != value)
                {
                    OnConfiguracionIdChanging(value);
                    ReportPropertyChanging("ConfiguracionId");
                    _ConfiguracionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfiguracionId");
                    OnConfiguracionIdChanged();
                }
            }
        }
        private global::System.Int32 _ConfiguracionId;
        partial void OnConfiguracionIdChanging(global::System.Int32 value);
        partial void OnConfiguracionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config1
        {
            get
            {
                return _Config1;
            }
            set
            {
                OnConfig1Changing(value);
                ReportPropertyChanging("Config1");
                _Config1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config1");
                OnConfig1Changed();
            }
        }
        private global::System.String _Config1;
        partial void OnConfig1Changing(global::System.String value);
        partial void OnConfig1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config2
        {
            get
            {
                return _Config2;
            }
            set
            {
                OnConfig2Changing(value);
                ReportPropertyChanging("Config2");
                _Config2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config2");
                OnConfig2Changed();
            }
        }
        private global::System.String _Config2;
        partial void OnConfig2Changing(global::System.String value);
        partial void OnConfig2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config3
        {
            get
            {
                return _Config3;
            }
            set
            {
                OnConfig3Changing(value);
                ReportPropertyChanging("Config3");
                _Config3 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config3");
                OnConfig3Changed();
            }
        }
        private global::System.String _Config3;
        partial void OnConfig3Changing(global::System.String value);
        partial void OnConfig3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config4
        {
            get
            {
                return _Config4;
            }
            set
            {
                OnConfig4Changing(value);
                ReportPropertyChanging("Config4");
                _Config4 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config4");
                OnConfig4Changed();
            }
        }
        private global::System.String _Config4;
        partial void OnConfig4Changing(global::System.String value);
        partial void OnConfig4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config5
        {
            get
            {
                return _Config5;
            }
            set
            {
                OnConfig5Changing(value);
                ReportPropertyChanging("Config5");
                _Config5 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config5");
                OnConfig5Changed();
            }
        }
        private global::System.String _Config5;
        partial void OnConfig5Changing(global::System.String value);
        partial void OnConfig5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config6
        {
            get
            {
                return _Config6;
            }
            set
            {
                OnConfig6Changing(value);
                ReportPropertyChanging("Config6");
                _Config6 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config6");
                OnConfig6Changed();
            }
        }
        private global::System.String _Config6;
        partial void OnConfig6Changing(global::System.String value);
        partial void OnConfig6Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Especial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Especial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Especial object.
        /// </summary>
        /// <param name="especialId">Initial value of the EspecialId property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="fechaInicio">Initial value of the FechaInicio property.</param>
        /// <param name="fechaTermino">Initial value of the FechaTermino property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="productoProductoId">Initial value of the ProductoProductoId property.</param>
        public static Especial CreateEspecial(global::System.Int32 especialId, global::System.String nombre, global::System.String descripcion, global::System.DateTime fechaInicio, global::System.DateTime fechaTermino, global::System.Double precio, global::System.Int32 productoProductoId)
        {
            Especial especial = new Especial();
            especial.EspecialId = especialId;
            especial.Nombre = nombre;
            especial.Descripcion = descripcion;
            especial.FechaInicio = fechaInicio;
            especial.FechaTermino = fechaTermino;
            especial.Precio = precio;
            especial.ProductoProductoId = productoProductoId;
            return especial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EspecialId
        {
            get
            {
                return _EspecialId;
            }
            set
            {
                if (_EspecialId != value)
                {
                    OnEspecialIdChanging(value);
                    ReportPropertyChanging("EspecialId");
                    _EspecialId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EspecialId");
                    OnEspecialIdChanged();
                }
            }
        }
        private global::System.Int32 _EspecialId;
        partial void OnEspecialIdChanging(global::System.Int32 value);
        partial void OnEspecialIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private global::System.DateTime _FechaInicio;
        partial void OnFechaInicioChanging(global::System.DateTime value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaTermino
        {
            get
            {
                return _FechaTermino;
            }
            set
            {
                OnFechaTerminoChanging(value);
                ReportPropertyChanging("FechaTermino");
                _FechaTermino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaTermino");
                OnFechaTerminoChanged();
            }
        }
        private global::System.DateTime _FechaTermino;
        partial void OnFechaTerminoChanging(global::System.DateTime value);
        partial void OnFechaTerminoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Double _Precio;
        partial void OnPrecioChanging(global::System.Double value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductoProductoId
        {
            get
            {
                return _ProductoProductoId;
            }
            set
            {
                OnProductoProductoIdChanging(value);
                ReportPropertyChanging("ProductoProductoId");
                _ProductoProductoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductoProductoId");
                OnProductoProductoIdChanged();
            }
        }
        private global::System.Int32 _ProductoProductoId;
        partial void OnProductoProductoIdChanging(global::System.Int32 value);
        partial void OnProductoProductoIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoEspecial", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoEspecial", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoEspecial", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoEspecial", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("EntityDataModel.ProductoEspecial", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Ingrediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingrediente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingrediente object.
        /// </summary>
        /// <param name="ingredienteId">Initial value of the IngredienteId property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        /// <param name="productoProductoId">Initial value of the ProductoProductoId property.</param>
        /// <param name="inventarioInventarioId">Initial value of the InventarioInventarioId property.</param>
        /// <param name="unidadUnidadId">Initial value of the UnidadUnidadId property.</param>
        public static Ingrediente CreateIngrediente(global::System.Int32 ingredienteId, global::System.Int32 cantidad, global::System.Int32 productoProductoId, global::System.Int32 inventarioInventarioId, global::System.Int32 unidadUnidadId)
        {
            Ingrediente ingrediente = new Ingrediente();
            ingrediente.IngredienteId = ingredienteId;
            ingrediente.Cantidad = cantidad;
            ingrediente.ProductoProductoId = productoProductoId;
            ingrediente.InventarioInventarioId = inventarioInventarioId;
            ingrediente.UnidadUnidadId = unidadUnidadId;
            return ingrediente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredienteId
        {
            get
            {
                return _IngredienteId;
            }
            set
            {
                if (_IngredienteId != value)
                {
                    OnIngredienteIdChanging(value);
                    ReportPropertyChanging("IngredienteId");
                    _IngredienteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IngredienteId");
                    OnIngredienteIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredienteId;
        partial void OnIngredienteIdChanging(global::System.Int32 value);
        partial void OnIngredienteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductoProductoId
        {
            get
            {
                return _ProductoProductoId;
            }
            set
            {
                OnProductoProductoIdChanging(value);
                ReportPropertyChanging("ProductoProductoId");
                _ProductoProductoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductoProductoId");
                OnProductoProductoIdChanged();
            }
        }
        private global::System.Int32 _ProductoProductoId;
        partial void OnProductoProductoIdChanging(global::System.Int32 value);
        partial void OnProductoProductoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InventarioInventarioId
        {
            get
            {
                return _InventarioInventarioId;
            }
            set
            {
                OnInventarioInventarioIdChanging(value);
                ReportPropertyChanging("InventarioInventarioId");
                _InventarioInventarioId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InventarioInventarioId");
                OnInventarioInventarioIdChanged();
            }
        }
        private global::System.Int32 _InventarioInventarioId;
        partial void OnInventarioInventarioIdChanging(global::System.Int32 value);
        partial void OnInventarioInventarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnidadUnidadId
        {
            get
            {
                return _UnidadUnidadId;
            }
            set
            {
                OnUnidadUnidadIdChanging(value);
                ReportPropertyChanging("UnidadUnidadId");
                _UnidadUnidadId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnidadUnidadId");
                OnUnidadUnidadIdChanged();
            }
        }
        private global::System.Int32 _UnidadUnidadId;
        partial void OnUnidadUnidadIdChanging(global::System.Int32 value);
        partial void OnUnidadUnidadIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoIngrediente", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoIngrediente", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoIngrediente", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoIngrediente", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("EntityDataModel.ProductoIngrediente", "Producto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "InventarioIngrediente", "Inventario")]
        public Inventario Inventario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventario>("EntityDataModel.InventarioIngrediente", "Inventario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventario>("EntityDataModel.InventarioIngrediente", "Inventario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Inventario> InventarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventario>("EntityDataModel.InventarioIngrediente", "Inventario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Inventario>("EntityDataModel.InventarioIngrediente", "Inventario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "UnidadIngrediente", "Unidad")]
        public Unidad Unidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadIngrediente", "Unidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadIngrediente", "Unidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unidad> UnidadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadIngrediente", "Unidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unidad>("EntityDataModel.UnidadIngrediente", "Unidad", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Inventario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inventario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Inventario object.
        /// </summary>
        /// <param name="inventarioId">Initial value of the InventarioId property.</param>
        /// <param name="cantidadTotal">Initial value of the CantidadTotal property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="unidadUnidadId">Initial value of the UnidadUnidadId property.</param>
        public static Inventario CreateInventario(global::System.Int32 inventarioId, global::System.Int32 cantidadTotal, global::System.String nombre, global::System.Int32 unidadUnidadId)
        {
            Inventario inventario = new Inventario();
            inventario.InventarioId = inventarioId;
            inventario.CantidadTotal = cantidadTotal;
            inventario.Nombre = nombre;
            inventario.UnidadUnidadId = unidadUnidadId;
            return inventario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InventarioId
        {
            get
            {
                return _InventarioId;
            }
            set
            {
                if (_InventarioId != value)
                {
                    OnInventarioIdChanging(value);
                    ReportPropertyChanging("InventarioId");
                    _InventarioId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InventarioId");
                    OnInventarioIdChanged();
                }
            }
        }
        private global::System.Int32 _InventarioId;
        partial void OnInventarioIdChanging(global::System.Int32 value);
        partial void OnInventarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantidadTotal
        {
            get
            {
                return _CantidadTotal;
            }
            set
            {
                OnCantidadTotalChanging(value);
                ReportPropertyChanging("CantidadTotal");
                _CantidadTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CantidadTotal");
                OnCantidadTotalChanged();
            }
        }
        private global::System.Int32 _CantidadTotal;
        partial void OnCantidadTotalChanging(global::System.Int32 value);
        partial void OnCantidadTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnidadUnidadId
        {
            get
            {
                return _UnidadUnidadId;
            }
            set
            {
                OnUnidadUnidadIdChanging(value);
                ReportPropertyChanging("UnidadUnidadId");
                _UnidadUnidadId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnidadUnidadId");
                OnUnidadUnidadIdChanged();
            }
        }
        private global::System.Int32 _UnidadUnidadId;
        partial void OnUnidadUnidadIdChanging(global::System.Int32 value);
        partial void OnUnidadUnidadIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "InventarioIngrediente", "Ingrediente")]
        public EntityCollection<Ingrediente> Ingredientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingrediente>("EntityDataModel.InventarioIngrediente", "Ingrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingrediente>("EntityDataModel.InventarioIngrediente", "Ingrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "UnidadInventario", "Unidad")]
        public Unidad Unidad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadInventario", "Unidad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadInventario", "Unidad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unidad> UnidadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unidad>("EntityDataModel.UnidadInventario", "Unidad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unidad>("EntityDataModel.UnidadInventario", "Unidad", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Orden")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Orden : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Orden object.
        /// </summary>
        /// <param name="ordenId">Initial value of the OrdenId property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        /// <param name="ordenado">Initial value of the Ordenado property.</param>
        /// <param name="clienteClienteId">Initial value of the ClienteClienteId property.</param>
        /// <param name="productoProductoId">Initial value of the ProductoProductoId property.</param>
        public static Orden CreateOrden(global::System.Int32 ordenId, global::System.Int32 cantidad, global::System.DateTime ordenado, global::System.Int32 clienteClienteId, global::System.Int32 productoProductoId)
        {
            Orden orden = new Orden();
            orden.OrdenId = ordenId;
            orden.Cantidad = cantidad;
            orden.Ordenado = ordenado;
            orden.ClienteClienteId = clienteClienteId;
            orden.ProductoProductoId = productoProductoId;
            return orden;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrdenId
        {
            get
            {
                return _OrdenId;
            }
            set
            {
                if (_OrdenId != value)
                {
                    OnOrdenIdChanging(value);
                    ReportPropertyChanging("OrdenId");
                    _OrdenId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrdenId");
                    OnOrdenIdChanged();
                }
            }
        }
        private global::System.Int32 _OrdenId;
        partial void OnOrdenIdChanging(global::System.Int32 value);
        partial void OnOrdenIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Ordenado
        {
            get
            {
                return _Ordenado;
            }
            set
            {
                OnOrdenadoChanging(value);
                ReportPropertyChanging("Ordenado");
                _Ordenado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ordenado");
                OnOrdenadoChanged();
            }
        }
        private global::System.DateTime _Ordenado;
        partial void OnOrdenadoChanging(global::System.DateTime value);
        partial void OnOrdenadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteClienteId
        {
            get
            {
                return _ClienteClienteId;
            }
            set
            {
                OnClienteClienteIdChanging(value);
                ReportPropertyChanging("ClienteClienteId");
                _ClienteClienteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClienteClienteId");
                OnClienteClienteIdChanged();
            }
        }
        private global::System.Int32 _ClienteClienteId;
        partial void OnClienteClienteIdChanging(global::System.Int32 value);
        partial void OnClienteClienteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductoProductoId
        {
            get
            {
                return _ProductoProductoId;
            }
            set
            {
                OnProductoProductoIdChanging(value);
                ReportPropertyChanging("ProductoProductoId");
                _ProductoProductoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductoProductoId");
                OnProductoProductoIdChanged();
            }
        }
        private global::System.Int32 _ProductoProductoId;
        partial void OnProductoProductoIdChanging(global::System.Int32 value);
        partial void OnProductoProductoIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ClienteOrden", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EntityDataModel.ClienteOrden", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EntityDataModel.ClienteOrden", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("EntityDataModel.ClienteOrden", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("EntityDataModel.ClienteOrden", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoOrden", "Producto")]
        public Producto Producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoOrden", "Producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoOrden", "Producto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Producto> ProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Producto>("EntityDataModel.ProductoOrden", "Producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Producto>("EntityDataModel.ProductoOrden", "Producto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Producto object.
        /// </summary>
        /// <param name="productoId">Initial value of the ProductoId property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="visible">Initial value of the Visible property.</param>
        /// <param name="imagePath">Initial value of the ImagePath property.</param>
        public static Producto CreateProducto(global::System.Int32 productoId, global::System.String nombre, global::System.String descripcion, global::System.Double precio, global::System.Boolean visible, global::System.String imagePath)
        {
            Producto producto = new Producto();
            producto.ProductoId = productoId;
            producto.Nombre = nombre;
            producto.Descripcion = descripcion;
            producto.Precio = precio;
            producto.Visible = visible;
            producto.ImagePath = imagePath;
            return producto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductoId
        {
            get
            {
                return _ProductoId;
            }
            set
            {
                if (_ProductoId != value)
                {
                    OnProductoIdChanging(value);
                    ReportPropertyChanging("ProductoId");
                    _ProductoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductoId");
                    OnProductoIdChanged();
                }
            }
        }
        private global::System.Int32 _ProductoId;
        partial void OnProductoIdChanging(global::System.Int32 value);
        partial void OnProductoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Double _Precio;
        partial void OnPrecioChanging(global::System.Double value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private global::System.Boolean _Visible;
        partial void OnVisibleChanging(global::System.Boolean value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoOrden", "Orden")]
        public EntityCollection<Orden> Ordenes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orden>("EntityDataModel.ProductoOrden", "Orden");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orden>("EntityDataModel.ProductoOrden", "Orden", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoEspecial", "Especial")]
        public EntityCollection<Especial> Especiales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Especial>("EntityDataModel.ProductoEspecial", "Especial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Especial>("EntityDataModel.ProductoEspecial", "Especial", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "ProductoIngrediente", "Ingrediente")]
        public EntityCollection<Ingrediente> Ingredientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingrediente>("EntityDataModel.ProductoIngrediente", "Ingrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingrediente>("EntityDataModel.ProductoIngrediente", "Ingrediente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Unidad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Unidad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Unidad object.
        /// </summary>
        /// <param name="unidadId">Initial value of the UnidadId property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Unidad CreateUnidad(global::System.Int32 unidadId, global::System.String nombre)
        {
            Unidad unidad = new Unidad();
            unidad.UnidadId = unidadId;
            unidad.Nombre = nombre;
            return unidad;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnidadId
        {
            get
            {
                return _UnidadId;
            }
            set
            {
                if (_UnidadId != value)
                {
                    OnUnidadIdChanging(value);
                    ReportPropertyChanging("UnidadId");
                    _UnidadId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UnidadId");
                    OnUnidadIdChanged();
                }
            }
        }
        private global::System.Int32 _UnidadId;
        partial void OnUnidadIdChanging(global::System.Int32 value);
        partial void OnUnidadIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "UnidadIngrediente", "Ingrediente")]
        public EntityCollection<Ingrediente> Ingredientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingrediente>("EntityDataModel.UnidadIngrediente", "Ingrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingrediente>("EntityDataModel.UnidadIngrediente", "Ingrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "UnidadInventario", "Inventario")]
        public EntityCollection<Inventario> Inventarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inventario>("EntityDataModel.UnidadInventario", "Inventario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inventario>("EntityDataModel.UnidadInventario", "Inventario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
